### ISSUE TITLE
FE cleanup

### ISSUE THREAD

**Issue by zahhar** [epam/corgis#213]
- [x] Remove Donate block on Create new Corgi page, change "Mint Corgi" button name to "Mint Corgi for 0.1N"
- [x] When user Trades Corgi, navigate him to the Corgi page so s_he can see that Auction has started
- [x] When new Corgi is minted, navigate user after succesfull payment to the Newly minted Corgi page
- [x] List of Corgis in the marketplace: show remaining time and current highest bid instead of "Minted by..." line
- [x] Change message "Gifted N min ago" to "Transferred "
- [ ] "Tongue" bug

**Comment by ohexus** [comment]
The "Tongue" bug can be reproduced only in Chromium based browsers. Unable to fix it now due to unstable experimental feature "cross-origin isolation" required in SharedArrayBuffer. More information [here](https://developer.chrome.com/blog/enabling-shared-array-buffer/).

**Comment by ohexus** [comment]
The "Tongue" bug can be reproduced only in Chromium based browsers. Unable to fix it now due to unstable "cross-origin isolation" feature required in SharedArrayBuffer. More information [here](https://developer.chrome.com/blog/enabling-shared-array-buffer/).
