### ISSUE TITLE
Extra: upgrade near-sdk-rs to v3

### ISSUE THREAD

**Issue by zahhar** [epam/corgis#218]
As soon as v3 becomes officially released: https://github.com/near/near-sdk-rs

**Comment by zahhar** [comment]
@acuarica  - are we fine to merge 3.0 to Main branch and upstream?

**Comment by acuarica** [comment]
It is already deployed to pages and it seems fine for now. I believe it can be pushed to upstream safely.

**Comment by zahhar** [comment]
@acuarica - then please close this issue, and let;'s prepare for upstream! Well done, thank you!
