### ISSUE TITLE
Rewrite minting into Rust

### ISSUE THREAD

**Issue by zahhar** [epam/corgis#38]
As per discussion with Matt in Discord: 
- goal is to use Rust for smartcontracts, not AssemblyScript - because it is long-term vision for NEAR and preferred way of defining smart-contracts (James: "_Rust is preferred by the core devs because there is a need to focus on supporting one language the best they can_")
- contract features to be limited to **Minting / Transferring / Moving** corgies (Matt: "_1 for the actual items and primary sale._")

Try to use same interface to avoid much changes on th FE side. 

Open question: what about randomly generating Corgie color also?

**Comment by acuarica** [comment]
Fixed in #66.
