### ISSUE TITLE
Reorganize code into Monorepo

### ISSUE THREAD

**Issue by zahhar** [epam/corgis#42]
We are and will remain a single git repo with at least 2 parts: React FE and Rust smart-contract (aka backend, that later can also incorporate existing AssemblyScript smart-contract example).

Now those two are tightly coupled: we have common package.json with scripts that attempt to build and deploy both FE and BE simultaneously, that is rarely needed. Additionally, it is hard to switch between DEV/TEST/PROD environments - both on BE as well as on FE side. 

FE does not have /tests directory, and if it will be added now - it can be confused with BE tests. And many more issues.

Proposal:

```
.github                  // CI flow configuration (GitHub Actions)
src/
  index.js
  //all other files  
test/
  //everything to test FE
LICENSE              // license file. included in npm artifact
package.json         // package-specific deps and scripts
README.md            // shown in npmjs.com. included in npm artifact
.eslintignore            // eslint (linter) ignored directories/files
.eslintrc                // eslint (linter) configuration

contract/
  //rust contract

.gitignore               // github's default node gitignore with customizations
```

Example: https://github.com/wixplosives/sample-monorepo

**Comment by acuarica** [comment]
Fixed in #66.
