### ISSUE TITLE
Logout URL does not 

### ISSUE THREAD

**Issue by zahhar** [epam/corgis#43]
WHEN: FE is deployed to GH Pages that has subdirectory (https://epam.github.io/corgis/), 
AND: user logs out from the app
EXPECTED: user is redirected to homepage https://epam.github.io/corgis/
BUT ACTUALLY: user gets redirected to https://epam.github.io/ (domain URL)

**Comment by ohexus** [comment]
Reopened because the issue has not been resolved

**Comment by ohexus** [comment]
Reopened because of wrong exact parameter

**Comment by ohexus** [comment]
Closed due to wrong reopen :)
